spring:
  application:
    name: 'template-spring-boot'
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: 'admin'
    password: 'secret'
    url: 'jdbc:postgresql://localhost:5432/template-spring-boot-db'
  kafka:
    topic: 'main-topic'
    partitions: 1
    replication-factor: 1
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'main-group'